#!/usr/bin/env node

var pkg = require('./package.json'),
    program = require('commander'),
    Bot = require('./lib/bot.js').Bot;
    logger = require('./lib/logger.js');


// Inject API keys from environment variables.
program.apiKeys = {
    'BITSTAMP_CLIENT_ID': process.env.BITSTAMP_CLIENT_ID,
    'BITSTAMP_KEY': process.env.BITSTAMP_KEY,
    'BITSTAMP_SECRET': process.env.BITSTAMP_SECRET,
    'BITME_KEY': process.env.BITME_KEY,
    'BITME_SECRET': process.env.BITME_SECRET
}


var printApiKeys = function() {
    // Print API key instructions
    console.log('  API keys loaded from environment variables:\n');

    for (var key in program.apiKeys) {
        var bullet = program.apiKeys[key] ? '✓' : '✖';
        console.log('    ' + bullet + ' ' + key);
    }

    console.log('');
};

program
    .version(pkg.version)
    .option('--LIVE', 'Use real APIs, instead of DummyExchanges.')
    .option('--resetOnly', 'Start and shutdown immediately after reset.')
    .option('--pretend', '(When live) Don\'t send trades, only print them.')
    .option('--premium <multiplier>', 'Multiplier to apply over remote exchange prices.', parseFloat)
    .option('--minValue <value>', 'Aggregate orders until their total value exceeds this.', parseFloat)
    .option('--maxOrders <value>', 'Maximum number of orders to maintain on the origin exchange.', parseInt)
    .option('--stopAfter <count>', 'Stop after there have been this many pending trades on the remote exchange.', parseInt)
    .option('--email [address]', 'Send alert-level logs to this email address.')
    .option('-v, --verbosity [level]', 'Set logging level verbosity (warn, info, debug). [info]')
    .on('--help', printApiKeys);

program.parse(process.argv);


// Determine logger verbosity.
var level = program.verbosity;
if (level === true) {  // true gets translated to 'debug'
    level = 'debug';
} else if (level === undefined) { // default 'info'
    level = 'info';
}
logger.level = level;

// Install email transport for winston?
if (program.email) {
    // TODO: Expose more of this configuration?
    var emailOptions = {
        to: program.email,
        level: 'alert'
    };
    logger.add(logger.transports.Mail, emailOptions);
}


// Prepare the bot.
var bot = Bot.fromConfig(program);

// Register signal handlers for graceful shutdown.
var gracefulShutdown = function(err) {
    logger.warn('Shutdown signal caught. Attempting to stop gracefully...');
    bot.stop();

    if (err) {
        logger.alert('Unexpected error triggered shutdown: %s\n', err.message, err.stack);
    }
};
process.on('SIGINT', gracefulShutdown);
process.on('uncaughtException', gracefulShutdown);
// TODO: Use nodejs domains for more resilient error handling? http://nodejs.org/api/domain.html


// Start trading.
bot.start();
